### ISSUE TITLE
Is it also possible to release the reproduced implementation of Self-Debugging?

### ISSUE THREAD

**Issue by allanj** [FloridSleeves/LLMDebugger#2]
Thanks a lot for the efforts again.

Or if it is not elegant to incorporate that code, is it possible to send it to me? 
allannlp.jie@gmail.com

**Comment by FloridSleeves** [comment]
Thank you for your interest in our research. Unfortunately, we're unable to share the reproduced implementation of Self-Debugging as the original authors might undergo their own release plans. We respect their intellectual property rights and can't distribute it without proper authorization. However, we're open to discussing the methodology used and providing insights. Basically, we follow the prompts provided in their paper Appendix F.5, F.6, F.9, F.10, G.4, G.7, G.8. Feel free to ask specific questions, and we'll do our best to provide our experience.

**Comment by allanj** [comment]
Thanks!
