### ISSUE TITLE
About the seed program

### ISSUE THREAD

**Issue by huanhuan6666** [FloridSleeves/LLMDebugger#6]
Thank you for your work. I would like to inquire about the seed programs mentioned in the paper (Section 3.2, 'Compared Methods'). Specifically, I am interested in where the Baseline (w/o debugger) seed programs were obtained, how these programs and their corresponding results were collected, and whether the existing programs were executed or if new sampling was conducted.

**Comment by huanhuan6666** [comment]
Another question concerns the temperature used in the 'Repeated Sampling' method shown in Figure 3. Based on my understanding, it should not be a greedy decoding process; otherwise, repeated sampling would be meaningless. So, what are the specific settings for the temperature? Of course, it should be noted that the LLM does not strictly adhere to greedy decoding.

**Comment by zlwang-cs** [comment]
Hi @huanhuan6666, Thanks for your interests in our work! As for the Baseline (w/o debugger), we simply call the corresponding LLM for the generated programs. They are also used as our seed programs so you can check them in our repo. The only exception is the Reflexion, where we directly use the provided generation results from the official repo as the seed programs.

As for the repeated sampling, your understanding is correct. We set temperature as 1.0 to avoid generating the same program all the time.
