### ISSUE TITLE
gpt-3.5-turbo-0613 has been deprecated by OpenAI

### ISSUE THREAD

**Issue by TedSIWEILIU** [FloridSleeves/LLMDebugger#8]
Hi, I notice that gpt-3.5-turbo-0613 has been deprecated by OpenAI. Hence, if you choose gpt-3.5-turbo-0613 as the model, the program will fail.

**Comment by FloridSleeves** [comment]
Thank you for the reminder. Just update the code to enable other models aside from `gpt-3.5-turbo-0613`.

**Comment by TedSIWEILIU** [comment]
> Thank you for the reminder. Just update the code to enable other models aside from `gpt-3.5-turbo-0613`.

Great. Thanks.
