### ISSUE TITLE
Generated code evaluation

### ISSUE THREAD

**Issue by TedSIWEILIU** [FloridSleeves/LLMDebugger#9]
Hi, thanks for addressing the previous question. I have generated some code based on the instructions but couldn't find the corresponding code for evaluating those generated codes to reproduce some performance e.g., Table 1 in your paper. If you could share the evaluation part of the code, it would greatly speed up my experiments. 

Thanks in advance.

**Comment by FloridSleeves** [comment]
The performance is counted by how many jsonlines in the output have the field `is_solved` and the value is `true`.

**Comment by TedSIWEILIU** [comment]
Thanks for your reply.
